gasweb/urls.py
from django.urls import path
from gasmenu import views

urlpatterns = [
    path('', views.index),
    path('register/', views.register),
    path('login/', views.login_view),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('logout/', views.logout_view),
    path('change/', views.change),
    path('change/<username>/', views.change),
    path('ingresar_solicitud/', views.ingresar_solicitud, name='ingresar_solicitud'),
    path('buscar_solicitud/', views.buscar_solicitud, name='buscar_solicitud'),
    path('detalle_solicitud/<int:solicitud_id>/', views.detalle_solicitud, name='detalle_solicitud'),
    path('listar_solicitudes/', views.listar_solicitudes, name='listar_solicitudes'),
    path('detalle_solicitud/<int:solicitud_id>/', views.detalle_solicitud, name='detalle_solicitud'),
    path('editar_solicitud/<int:solicitud_id>/', views.editar_solicitud, name='editar_solicitud'),
    path('cambiar_estado/<int:solicitud_id>/', views.cambiar_estado, name='cambiar_estado'),
    path('confirmar_eliminacion/<int:solicitud_id>/', views.confirmar_eliminacion, name='confirmar_eliminacion'),
    path('crear_usuario/', views.crear_usuarios, name='crear_usuario'),
    path('confirmar_eliminacion_usuario/<str:username>/', views.confirmar_eliminacion_usuario, name='confirmar_eliminacion_usuario'),
    path('usuario/<str:username>/', views.detalles_usuario, name='detalles_usuario'),
    path('usuario/editar/<str:username>/', views.editar_usuario, name='editar_usuario'),


]

gasmenu/models.py
from django.db import models

class Solicitud(models.Model):
    ESTADOS = (
        ('pendiente', 'Pendiente'),
        ('aceptada', 'Aceptada'),
        ('rechazada', 'Rechazada'),
        ('expirada', 'Expirada'),
    )

    rut = models.CharField(max_length=12)
    nombre = models.CharField(max_length=100)
    apellidos = models.CharField(max_length=100)
    direccion = models.CharField(max_length=200)
    telefono = models.CharField(max_length=15)
    comuna = models.CharField(max_length=100)
    estado = models.CharField(max_length=10, choices=ESTADOS, default='pendiente')

    def __str__(self):
        return f"{self.nombre} {self.apellidos} - {self.estado}"

templates/web/buscar_solicitud.html
{% extends 'logins/base.html' %}

{% block content %}
<form method="get" action="{% url 'buscar_solicitud' %}">
    <div class="mb-3">
        <label for="buscarRUT" class="form-label">Buscar por RUT:</label>
        <input type="text" class="form-control" id="buscarRUT" name="rut" placeholder="Ingrese RUT">
    </div>
    <button type="submit" class="btn btn-primary">Buscar</button>
</form>


{% if resultados %}
    <h2>Resultados de la búsqueda:</h2>
    <div class="resultados">
        {% for solicitud in resultados %}
            <div class="solicitud">
                <p>RUT: {{ solicitud.rut }}</p>
                <p>Nombre: {{ solicitud.nombre }}</p>
                <p>Apellidos: {{ solicitud.apellidos }}</p>
               
            </div>
        {% endfor %}
    </div>
{% else %}
    {% if query %}
        <p>No se encontraron solicitudes con el RUT proporcionado.</p>
    {% endif %}
{% endif %}
{% endblock content %}

templates/web/cambiar_estado.html
{% extends 'logins/base.html' %}

{% block content %}
<div class="container mt-3">
    <h2>Cambiar Estado de la Solicitud</h2>
    <form method="post" action="{% url 'cambiar_estado' solicitud.id %}">
        {% csrf_token %}
        <div class="mb-3">
            <label for="estado" class="form-label">Nuevo Estado</label>
            <select name="estado" id="estado" class="form-select">
                {% for estado, estado_display in solicitud.ESTADOS %}
                    <option value="{{ estado }}" {% if solicitud.estado == estado %} selected {% endif %}>
                        {{ estado_display }}
                    </option>
                {% endfor %}
            </select>
        </div>
        <button type="submit" class="btn btn-primary">Cambiar Estado</button>
        <a href="{% url 'listar_solicitudes' %}" class="btn btn-secondary">Cancelar</a>
    </form>
</div>
{% endblock content %}

templates/web/confirmar_eliminacion.html
{% extends 'logins/base.html' %}

{% block content %}
<div class="container mt-3">
    <h2>Confirmar Eliminación</h2>
    <p>¿Estás seguro de que deseas eliminar la solicitud "{{ solicitud.nombre }}" con RUT "{{ solicitud.rut }}"?</p>

    <form method="post" action="{% url 'confirmar_eliminacion' solicitud.id %}">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger btn-sm">Eliminar</button>
        <a href="{% url 'listar_solicitudes' %}" class="btn btn-secondary btn-sm">Cancelar</a>
    </form>
</div>
{% endblock content %}

templates/web/confirmar_eliminar_usuario.html
{% extends 'logins/base.html' %}

{% block content %}
  <div class="container">
    <h2>Confirmación de Eliminación</h2>
    <p>¿Estás seguro de que deseas eliminar al usuario "{{ usuario.username }}"?</p>
    
    <form action="{% url 'confirmar_eliminacion_usuario' usuario.username %}" method="post">
      {% csrf_token %}
      <input type="submit" value="Eliminar Usuario" class="btn btn-danger">
      <a href="/dashboard" class="btn btn-secondary">Cancelar</a>
    </form>
  </div>
{% endblock content %}

templates/web/crear_usuarios.html
{% extends 'logins/base.html' %}

{% block content %}
<div class="container mt-4">
    <h2 class="mb-4">Crear Nuevo Usuario</h2>
    <form method="post" class="border p-4 rounded bg-light">
        {% csrf_token %}
        <div class="mb-3">
            <label for="first-name" class="form-label">Nombre</label>
            <input type="text" class="form-control" id="first-name" name="first-name" placeholder="Ingrese su nombre" required>
        </div>
        <div class="mb-3">
            <label for="password" class="form-label">Contraseña</label>
            <input type="password" class="form-control" id="password" name="password" required>
        </div>
        <div class="mb-3">
            <label for="confirm_password" class="form-label">Confirmar Contraseña</label>
            <input type="password" class="form-control" id="confirm_password" name="confirm_password" required>
        </div>
        <div class="mb-3">
            <label for="email" class="form-label">Correo Electrónico (Nombre de Usuario)</label>
            <input type="email" class="form-control" id="email" name="email" required>
        </div>
        <div class="mb-3 form-check">
            <input type="checkbox" class="form-check-input" id="superuser" name="superuser">
            <label class="form-check-label" for="superuser">Marcar como Superusuario</label>
        </div>
        <div class="text-center">
            <button type="submit" class="btn btn-primary">Crear Usuario</button>
        </div>
    </form>
</div>
{% endblock content %}

templates/web/detalle_solicitud.html
{% extends 'logins/base.html' %}

{% block content %}
<div class="card">
    <div class="card-header">
        Detalle de la Solicitud
    </div>
    <div class="card-body">
        <h5 class="card-title">{{ solicitud.nombre }}</h5>
        <p class="card-text">RUT: {{ solicitud.rut }}</p>
        <p class="card-text">Apellidos: {{ solicitud.apellidos }}</p>
        <p class="card-text">Dirección: {{ solicitud.direccion }}</p>
        <p class="card-text">Teléfono: {{ solicitud.telefono }}</p>
        <p class="card-text">Comuna: {{ solicitud.comuna }}</p>
        <p class="card-text">Estado: {{ solicitud.get_estado_display }}</p>
    
    </div>
</div>
{% endblock content %}

templates/web/detalles_usuario.html
{% extends 'logins/base.html' %}

{% block content %}
  <div class="container mt-3">
    <h2>Detalles del Usuario</h2>
    <div class="card">
      <div class="card-header">
        Información de Usuario
      </div>
      <ul class="list-group list-group-flush">
        <li class="list-group-item">Nombre de usuario: {{ usuario.username }}</li>
        <li class="list-group-item">Nombre: {{ usuario.first_name }} {{ usuario.last_name }}</li>
        <li class="list-group-item">Correo electrónico: {{ usuario.email }}</li>
    
      </ul>
    </div>
    <a href="{% url 'editar_usuario' usuario.username %}" class="btn btn-primary mt-3">Editar</a>
    <a href="{% url 'dashboard' %}" class="btn btn-secondary mt-3">Volver al Dashboard</a>
  </div>
{% endblock content %}

templates/web/editar_solicitud.html
{% extends 'logins/base.html' %}

{% block content %}
<div class="container mt-4">
    <h2 class="mb-4">Editar Solicitud {{ solicitud.id }}</h2>
    <form action="{% url 'editar_solicitud' solicitud.id %}" method="post">
        {% csrf_token %}
        
        <div class="card mb-3">
            <div class="card-body">
                <h5 class="card-title">Información Personal</h5>
                <div class="mb-3">
                    <label for="id_rut" class="form-label">RUT:</label>
                    <input type="text" class="form-control" name="rut" id="id_rut" value="{{ solicitud.rut }}" required>
                </div>
                <div class="mb-3">
                    <label for="id_nombre" class="form-label">Nombre:</label>
                    <input type="text" class="form-control" name="nombre" id="id_nombre" value="{{ solicitud.nombre }}" required>
                </div>
                <div class="mb-3">
                    <label for="id_apellidos" class="form-label">Apellidos:</label>
                    <input type="text" class="form-control" name="apellidos" id="id_apellidos" value="{{ solicitud.apellidos }}" required>
                </div>
            </div>
        </div>
        
        <div class="card mb-3">
            <div class="card-body">
                <h5 class="card-title">Información de Contacto</h5>
                <div class="mb-3">
                    <label for="id_direccion" class="form-label">Dirección:</label>
                    <input type="text" class="form-control" name="direccion" id="id_direccion" value="{{ solicitud.direccion }}" required>
                </div>
                <div class="mb-3">
                    <label for="id_telefono" class="form-label">Teléfono:</label>
                    <input type="text" class="form-control" name="telefono" id="id_telefono" value="{{ solicitud.telefono }}" required>
                </div>
                <div class="mb-3">
                    <label for="id_comuna" class="form-label">Comuna:</label>
                    <input type="text" class="form-control" name="comuna" id="id_comuna" value="{{ solicitud.comuna }}" required>
                </div>
            </div>
        </div>

        <button type="submit" class="btn btn-primary">Actualizar Solicitud</button>
    </form>
</div>
{% endblock content %}

templates/web/editar_usuario.html
{% extends 'logins/base.html' %}

{% block content %}
<div class="container mt-3">
    <h2>Editar Usuario</h2>
    <form method="post">
        {% csrf_token %}
        <div class="mb-3">
            <label  class="form-label">Nombre</label>
            <input class="form-control" type="text" name="first-name" placeholder="Ingrese su nombre" value="{{ user.first_name }}">
        </div>
        <div class="mb-3">
            <label for="email" class="form-label">Correo Electrónico (Nombre de Usuario)</label>
            <input type="email" class="form-control" id="email" name="email" required value="{{ user.email }}">
        </div>
        <div class="mb-3 form-check">
            <input type="checkbox" class="form-check-input" id="superuser" name="superuser" {% if user.is_superuser %}checked{% endif %}>
            <label class="form-check-label" for="superuser">Marcar como Superusuario</label>
        </div>
        <button type="submit" class="btn btn-primary">Actualizar Usuario</button>
    </form>
</div>
{% endblock content %}

templates/web/eliminar_usuarios.html
{% extends 'logins/base.html' %}
{% block content %}
{% endblock content %}

templates/web/ingresar_solicitud.html
{% extends 'logins/base.html' %}

{% block content %}
<div class="container mt-4">
    <div class="row justify-content-center">
        <div class="col-lg-6 col-md-8">
            <div class="card shadow">
                <div class="card-body">
                    <h2 class="card-title mb-4 text-center">Ingresar Solicitud de Descuento de Gas</h2>
                    <form action="/ingresar_solicitud/" method="post">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="id_rut" class="form-label">RUT:</label>
                            <input type="text" class="form-control" name="rut" id="id_rut" required>
                        </div>
                        <div class="mb-3">
                            <label for="id_nombre" class="form-label">Nombre:</label>
                            <input type="text" class="form-control" name="nombre" id="id_nombre" required>
                        </div>
                        <div class="mb-3">
                            <label for="id_apellidos" class="form-label">Apellidos:</label>
                            <input type="text" class="form-control" name="apellidos" id="id_apellidos" required>
                        </div>
                        <div class="mb-3">
                            <label for="id_direccion" class="form-label">Dirección:</label>
                            <input type="text" class="form-control" name="direccion" id="id_direccion" required>
                        </div>
                        <div class="mb-3">
                            <label for="id_telefono" class="form-label">Teléfono:</label>
                            <input type="text" class="form-control" name="telefono" id="id_telefono" required>
                        </div>
                        <div class="mb-3">
                            <label for="id_comuna" class="form-label">Comuna:</label>
                            <input type="text" class="form-control" name="comuna" id="id_comuna" required>
                        </div>
                        <div class="text-center">
                            <button type="submit" class="btn btn-primary">Enviar Solicitud</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

templates/web/listar_solicitudes.html
{% extends 'logins/base.html' %}

{% block content %}
<div class="container mt-3">
    <h2>Listado de Solicitudes</h2>
    <table class="table table-striped mt-3">
        <thead class="table-dark">
            <tr>
                <th>RUT</th>
                <th>Nombre</th>
                <th>Apellidos</th>
                <th>Acciones</th>
            </tr>
        </thead>
        <tbody>
            {% for solicitud in solicitudes %}
            <tr>
                <td>{{ solicitud.rut }}</td>
                <td>{{ solicitud.nombre }}</td>
                <td>{{ solicitud.apellidos }}</td>
                <td>
                    <!-- Botón de detalle -->
                    <a href="{% url 'detalle_solicitud' solicitud.id %}" class="btn btn-info btn-sm">Detalle</a>
                    
                    {% if user.is_superuser %}
                        <!-- Botón de editar -->
                        <a href="{% url 'editar_solicitud' solicitud.id %}" class="btn btn-secondary btn-sm">Editar</a>
                        
                        <!-- Botón de cambiar estado -->
                        <a href="{% url 'cambiar_estado' solicitud.id %}" class="btn btn-warning btn-sm">Cambiar Estado</a>
                        
                        <!-- Botón de eliminar -->
                        <a href="{% url 'confirmar_eliminacion' solicitud.id %}" class="btn btn-danger btn-sm">Eliminar</a>
                    {% endif %}
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock content %}